### ISSUE TITLE
No tests for (and not yet working on) LifeRay

### ISSUE THREAD

**Issue by enver-haase** [vaadin/portlet#179] opened 2020-04-08 14:46 UTC
While Pluto is an important target environment for one of our customers, Liferay support is expected and may even be used by the same customer before their own Portal Application running in the Pluto environment is implemented and released.

**Comment by pleku** [comment] 2020-04-08 15:04
How can a new portlet support be a bug ?

Regardless, this is a duplicate of https://github.com/vaadin/flow/issues/5815

**Closed by pleku** 2020-04-08 15:04 UTC
Labels: bug
