### ISSUE TITLE
Static bundle to serve portlets not working for Vaadin Flow v23

### ISSUE THREAD

**Issue by p-maraver** [vaadin/portlet#243] opened 2022-12-02 18:58 UTC
- It is reproducible with Address Book Portlet Demo for Liferay 7: https://github.com/vaadin/addressbook-portlet/tree/v23
- Serving 1 portlet like in base-starter-flow-portlet works fine, but when using the static bundle of address book all the portlets are empty when added to the portal page.
- Error:  WARN  [http-nio-8080-exec-7][code_jsp:157] {code="404", msg="ProxyServlet: /o/vaadin-portlet-static/VAADIN/build/vaadin-export-7455a290e542a726889a.cache.js", uri=/o/vaadin-portlet-static/VAADIN/build/vaadin-export-7455a290e542a726889a.cache.js}
- Versions:
    - Vaadin Portlet version: v2.0
    - Flow version: v23.1
    - Portal (Pluto) version: 3.1
    - Java version: 11
    - OS version: NA
    - Browser version (if applicable): NA

**Comment by mshabarov** [comment] 2022-12-08 12:40
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by krissvaa** [comment] 2022-12-08 14:12
When I did some investigation I found that:
Vaadin 14 used this structure:
`/o/vaadin-portlet-static/VAADIN/build/vaadin-export-7455a290e542a726889a.cache.js `
Vaadin 23 now used structure: 
`/o/vaadin-portlet-static/VAADIN/webapp/VAADIN/build/vaadin-export-7455a290e542a726889a.cache.js`
Vaadin 23 js  files can be used, just need to change the reference to them or change their placement to how it was in V14.
Couldn't yet find what(or why something) is referencing the vaadin-js files without `VAADIN/webapp/` part

**Comment by mcollovati** [comment] 2022-12-09 10:15
The problem here seems to be in the `addressbook-portlet` repository.

As @krissvaa mentioned something changed in static resources handling in Vaadin 23.
The `VAADIN/build/` folder as moved under `/VAADIN/webapp`, but the static bundle portlet should move them to the root of the WAR.
The issue is in the `addressbook-bundle/pom.xml` maven-war-plugin configuration.
The current config is the following

```xml
<webResources>
    <resource>
        <!-- this is relative to the pom.xml directory -->
        <directory>target/classes/META-INF/</directory>
        <!-- Include all files and folders below <directory> -->
        <includes>
            <include>**</include>
        </includes>
        <!-- do not include flow-build-info -->
        <excludes>
            <exclude>VAADIN/config/flow-build-info.json
            </exclude>
        </excludes>
    </resource>
</webResources>
```

but it should instead have 
```
<directory>target/classes/META-INF/VAADIN/webapp/</directory>
```

For development mode this is not enough because the `VAADIN/config/stats.json` is needed.
A working configuration is the following

```xml
<webResources>
    <resource>
        <!-- this is relative to the pom.xml directory -->
        <directory>target/classes/META-INF/VAADIN/webapp/</directory>
        <!-- Include all files and folders below <directory> -->
        <includes>
            <include>**</include>
        </includes>
        <!-- do not include flow-build-info -->
        <excludes>
            <exclude>VAADIN/config/flow-build-info.json
            </exclude>
        </excludes>
    </resource>
    <resource>
        <!-- this is relative to the pom.xml directory -->
        <directory>target/classes/META-INF/</directory>
        <!-- Include all files and folders below <directory> -->
        <includes>
            <include>VAADIN/config/**</include>
        </includes>
        <!-- do not include flow-build-info -->
        <excludes>
            <exclude>VAADIN/config/flow-build-info.json
            </exclude>
        </excludes>
    </resource>
</webResources>
```

So, action needed to close this ticket are:

* update documentation with the correct configuration for the maven-war-plugin
* fix the `addressbook-bundle` configuration int the `addressbok-portlet` demo

**Comment by mcollovati** [comment] 2022-12-09 11:29
Whereas the above configuration works for Vaadin 23.1, I can see errors with 23.2.
Seems something related to loading the `web-component.html` contents in development mode.

**Comment by mcollovati** [comment] 2022-12-09 12:04
The `web-component.html` problems is already mentioned in #240

**Comment by krissvaa** [comment] 2022-12-09 12:07
Only `web-component.html` problem is happening both with VITE and webpack - if `com.vaadin.experimental.webpackForFrontendBuild=true` is enabled. 
https://github.com/vaadin/portlet/issues/240 was strictly for VITE version.

**Closed** 2022-12-14 07:15 UTC
Labels: bug, documentation, impact: High, Severity: Blocker, workaround, BFP
